services:
  server:
    container_name: server
    image: server
    build:
      context: .
      dockerfile: ./server.Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    tty: true
    restart: always
