//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub use super::color::Entity as Color;
pub use super::connector::Entity as Connector;
pub use super::item::Entity as Item;
pub use super::label::Entity as Label;
pub use super::trash::Entity as Trash;
